version: "3"
  
networks:
  myNetwork:
    driver: bridge

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - myNetwork

  kafka:
    image: 'bitnami/kafka:latest'
    user: root
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      # - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    networks:
      - myNetwork
    depends_on:
      - zookeeper


  producer:
    image: kafka-producer/producer:latest
    build:
      context: ./producer
      # dockerfile: producer/Dockerfile
    ports:
      - "8282:80"
    depends_on:
      - kafka
    networks:
      - myNetwork

  consumer:
    image: peterc/kafka-flask-consumer-example:latest
    build:
      context: ./consumer
    ports:
      - "8283:80"
    depends_on:
      - kafka
    networks:
      - myNetwork

# consumer:
#     build: consumer
#     image: kafka-consumer/consumer:latest
#     environment:
#       - "SPRING_PROFILES_ACTIVE=${ACTIVE_PROFILE}"
#     ports:
#       - "8080:8080"
#     depends_on:
#       - kafka