version: "3.2"

# list of containers to be run
services:

  # rabbit_mq container uses the default rabbitmq image
  # exposes the ports
  # uses the specified volume
  rabbit_mq:

    # plugin for web dashboard
    image: rabbitmq:3.8-rc-management
    container_name: rabbit_mq
    ports:
        - '5672:5672'
        - '15672:15672'
    volumes:
      - rabbit_mqdata:/usr/share/rabbitmq/data

  # produces container builds the producer image
  # and produces message to the queue
  producer:
    build: producer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./producer:/usr/src/app/producer
      - ./mq_connector.py:/usr/src/app/producer/mq_connector.py

  # consumer container builds the consumer image
  consumer1:
    build: consumer
    depends_on:
        - rabbit_mq
    environment:
        AMQP_URL: 'amqp://rabbit_mq?connection_attempts=10&retry_delay=10'
    volumes:
      - ./consumer:/usr/src/app/consumer
      - ./mq_connector.py:/usr/src/app/consumer/mq_connector.py


volumes:
    rabbit_mqdata:
      driver: local